### ISSUE TITLE
Add GeoBR dataset

### ISSUE THREAD

**Issue by juliohm** [JuliaEarth/GeoArtifacts.jl#20]
We need a new submodule called `GeoBR` that ports the API of the https://github.com/ipeaGIT/geobr dataset.

From their docs, this is a simple example of the `read_municipality` function in R:

```R
# Read specific municipality at a given year
mun = read_municipality(code_muni=1200179, year=2017)
```

We need an equivalent function as follows:

```julia
mun = GeoBR.municipality(code=1200179, year=2017)
```

Given that we don't use underscore in our code style, we need to cleanup some of these function and argument names.

**Comment by aybanda** [comment]
/attempt #20


<div id="algora-attempt" />

| [Algora profile](https://console.algora.io/@/aybanda) | Completed bounties | Tech | Active attempts | Options |
| --- | --- | --- | --- | --- |
| @aybanda | 1 bounty from 1 project | <div align="center"></div> | <div align="center"></div> | [Cancel attempt](https://console.algora.io/api/bounties/cm0voh8ss0004jp037ks84xaz/cancel-attempt) |

**Comment by juliohm** [comment]
I've updated the description of the issue above for clarity.

**Comment by juliohm** [comment]
Fixed on master.
